---
title: "Interactive Map"
output: 
  html_document:
    theme: flatly
    toc: true
    code_folding: hide
    toc_float: true
---

```{r}
# 基本环境设置 -----------------------------------------------------------

library(tidyverse)
library(janitor)
library(sf)
library(tigris)
library(shiny)
library(leaflet)
library(viridisLite)

options(tigris_use_cache = TRUE)

```


```{r}
# 读取已经 merge 好的 ZIP × year × month 数据

df_merged <- readr::read_csv("data/zip_year_month_merged.csv") |>
clean_names() |>
mutate(zipcode = as.character(zipcode))

# 2.1 按 ZIP × 年聚合 -----------------------------------------------

zip_year <- df_merged |>
group_by(zipcode, year) |>
summarise(
rat_count_year  = sum(rat_count_zip_month, na.rm = TRUE),
violation_year  = sum(violation_count_zip_month, na.rm = TRUE),
inspection_year = sum(inspection_count_zip_month, na.rm = TRUE),
total_pop       = mean(total_pop, na.rm = TRUE),
.groups = "drop"
) |>
mutate(
rats_per_10000_year = 10000 * rat_count_year / total_pop,
viol_per_rest_year  = violation_year / inspection_year
)

# 2.2 获取 ZCTA 边界并与 ZIP 年度表合并 -----------------------------

ny_zcta <- zctas(state = "NY", year = 2010) |>
rename(zipcode = ZCTA5CE10) |>
mutate(zipcode = as.character(zipcode))

# 使用经纬度坐标 (EPSG:4326) 方便 leaflet 显示

ny_zip_year_sf <- ny_zcta |>
st_transform(4326) |>
left_join(zip_year, by = "zipcode") |>
filter(!is.na(year))

# 简单检查

dplyr::glimpse(ny_zip_year_sf)

```


```{r}

#-----------------#

# Shiny UI 部分

#-----------------#

ui <- fluidPage(
titlePanel("Interactive Map: Rats & Violations by Year (ZIP code)"),
sidebarLayout(
sidebarPanel(
sliderInput(
"year",
"Select year:",
min   = min(ny_zip_year_sf$year, na.rm = TRUE),
max   = max(ny_zip_year_sf$year, na.rm = TRUE),
value = min(ny_zip_year_sf$year, na.rm = TRUE),
step  = 1,
sep   = ""
),
tags$hr(),
h4("Clicked ZIP summary"),
verbatimTextOutput("info")
),
mainPanel(
leafletOutput("map", height = 600)
)
)
)

#-----------------#

# Shiny server 部分

#-----------------#

server <- function(input, output, session) {

# 根据 slider 选择的年份过滤数据

year_data <- reactive({
ny_zip_year_sf[ny_zip_year_sf$year == input$year, ]
})

# 用 rats_per_10000_year 设定颜色

pal <- colorNumeric(
palette = "cividis",
domain  = ny_zip_year_sf$rats_per_10000_year
)

# 绘制地图

output$map <- renderLeaflet({
leaflet(year_data()) |>
addTiles() |>
addPolygons(
fillColor   = ~pal(rats_per_10000_year),
fillOpacity = 0.8,
color       = "white",
weight      = 0.5,
layerId     = ~zipcode,
label = ~paste0(
"ZIP: ", zipcode,
"<br>Year: ", year,
"<br>Rats / 10,000: ",
round(rats_per_10000_year, 1),
"<br>Viol / Restaurant: ",
round(viol_per_rest_year, 2)
),
labelOptions = labelOptions(direction = "auto")
) |>
addLegend(
"bottomright",
pal    = pal,
values = ~rats_per_10000_year,
title  = "Rats / 10,000",
opacity = 0.8
)
})

# 点击 polygon 后在侧边栏显示详细数值

output$info <- renderPrint({
req(input$map_shape_click)
click <- input$map_shape_click
dat <- year_data() |> dplyr::filter(zipcode == click$id)


if (nrow(dat) == 0) return(NULL)

list(
  year                  = dat$year[1],
  zipcode               = dat$zipcode[1],
  rats_per_10000        = round(dat$rats_per_10000_year[1], 1),
  violations_per_rest   = round(dat$viol_per_rest_year[1], 3)
)


})
}

# 在 Rmd 中直接运行 Shiny app

shinyApp(ui, server)



```


